services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: webapi
      POSTGRES_PASSWORD: webapi
    ports:
      - 5432:5432
  micro_service:
    build: ./MicroService/.
    ports:
      - 5000:5000
  webapi:
    build: ./WebServer/.
    ports:
      - 5000:5000
    depends_on:
      - db
      - micro_service
  gateway:
    container_name: nginx
    build: ./nginx/
    ports: 
      - 80:80
    depends_on:
      - db
      - webapi
      - micro_service      