services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: identitydb
      POSTGRES_USER: webapi
      POSTGRES_PASSWORD: webapi
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "identitydb", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
  micro_service:
    container_name: micro_service
    build: ./MicroService/.
    environment:
      - ASPNETCORE=http://+:5000
    ports:
      - 5001:5000
  webapi:
    container_name: webapi
    build: ./WebServer/.
    environment:
      - ASPNETCORE=http://+:5000
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
      micro_service:
        condition: service_started
  gateway:
    container_name: nginx
    build: ./nginx/
    ports: 
      - 8000:80
    depends_on:
      - db
      - webapi
      - micro_service      