name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: run compose
        run: docker compose up -d 
      
      - name: stop compose
        run: docker compose down

      - name: push webapi
        run: |
          docker tag webapi:latest ${{ vars.DOCKERHUB_USERNAME }}/webapi:latest
          docker image push ${{ vars.DOCKERHUB_USERNAME }}/webapi:latest

      - name: push service
        run: |
          docker tag service:latest ${{ vars.DOCKERHUB_USERNAME }}/service:latest
          docker image push ${{ vars.DOCKERHUB_USERNAME }}/service:latest
     
